### ISSUE TITLE
it would be nice if there was an option to use mcera5 to download the correctly set up hourly data for use with microclimf

### ISSUE THREAD

**Issue by admahood** [dklinges9/mcera5#19]

**Comment by dklinges9** [comment]
Hi Adam,

mcera5-downloaded hourly ERA5 data can indeed interface with microclimf. You just need to use the function `microctools::hourlyncep_convert()` to convert the climate variables, see the last few lines of the [mcera5 vignette](https://github.com/dklinges9/mcera5/blob/master/vignettes/mcera5_vignette.Rmd). These data are then ready for use with `microclimf::modelin()` ([see here for details on that function](https://github.com/ilyamaclean/microclimf/blob/main/R/runfunctions.R)).

If you are referring to using gridded ERA5 data via mcera5, to use with `microclimf::modelina()`, that's something I hope to get a chance to add to the package in the next few weeks/months.

Best,
Dave

**Comment by dklinges9** [comment]
Hi Adam,

I'm letting you know that there are now several functions for handling ERA5 extraction across a spatial grid, `extract_clima()` and `extract_precipa()`.

I currently have these functions available only on a new dev branch rather than the main branch, while I'm still testing. You can install the dev branch by the following:
```
library(devtools)
install_github("dklinges9/mcera5", ref = "extract_clima_build")
```

Feel free to give these a spin and let me know if you have questions. I've replied to a similar issue opened [here](https://github.com/dklinges9/mcera5/issues/21), and will keep this issue open until I pull this dev branch into the main branch.

Best,
Dave

**Comment by dklinges9** [comment]
Closing this issue as it may be resolved, but feel free to re-open or submit a new issue. Best, Dave
