### ISSUE TITLE
How to extract data for an area instead of a point with extract_clim and extract_precip? 

### ISSUE THREAD

**Issue by veroandreo** [dklinges9/mcera5#21]
Hello, 

I'm a totally beginner with mcera5 and microclima. I have managed to download one year of ERA5 hourly data for a region covering a city in Argentina (OT: why not use ERA5 Land by default? It has better spatial resolution). 

Next, I want to downscale it to 100m using `microclima::runauto()`. However, it seems that `extract_clim()` and `extract_precip()` that AFAIU are supposed to prepare data to use with microclima only extract data for a single point. Is that right? I haven´t found examples in the vignettes nor elsewhere for more than one point or for an area. How can I extract the data for the whole area that I downloaded? Is that possible? I highly appreciate any pointers ;)

Thanks a lot in advance!

**Comment by dklinges9** [comment]
Hi Veronica,

Sorry for my late reply. You bring up two good features that other users have requested as well:
- support for ERA5-land instead of just ERA5
- extraction for a spatial area simultaneously instead of a single point

These are both things that I am hoping to deploy to the package in the new few weeks, so stay tuned!

**Comment by dklinges9** [comment]
Hi Veronica,

I'm letting you know that there are now several functions for handling ERA5 extraction across a spatial grid, `extract_clima()` and `extract_precipa()`.

I currently have these functions available only on a new dev branch rather than the main branch, while I'm still testing. You can install the dev branch by the following:
```
library(devtools)
install_github("dklinges9/mcera5", ref = "extract_clima_build")
```

Feel free to give these a spin and let me know if you have questions. I want to quickly note that `microclima::runauto()`, as you mention in your initial post, actually takes as input a data.frame of macroclimate for a single point, rather than a grid of macroclimate (and so `extract_clim()` and `extract_precip()` would be appropriate for `microclima::runauto()`). But these new functions will be of use for gridded microclimate predictions using the forthcoming `microclimf` package by Ilya Maclean, who also developed `microclima`.

Adding support for ERA5-land is next!
