### ISSUE TITLE
A few glitches caused by new CDS service and update to ecmwfr package

### ISSUE THREAD

**Issue by ilyamaclean** [dklinges9/mcera5#36]
The new CDS service has triggered some updates to the ecmwfr package. In the vignette, where you explain setting up user credentials, note that ecmwfr::wf_set_key function no longer accepts specifying a service, so drop service = "cds" from the example (i.e. should become wf_set_key(user = uid, key = cds_access_token).
 
Also I noticed that the format of the era5 nc file has changed a bit. I think the only thing this might affect is the ability to pick up the time stamp from the file. I noticed terra doesn’t manage this now, so not sure whether lubridate will. I get an error I didn't get before when calling extract_clima, which appeared to be related to the time stamp, but didn't investigate fully.

**Comment by dklinges9** [comment]
yep, I’ve been addressing these changes for the new CDS on a different branch, [new_cds_time_edits](https://github.com/dklinges9/mcera5/tree/new_cds_time_edits)

The reason I haven’t merged this to master as it would reduce compatibility with ERA5 data that users had queried from the old CDS, which I know some users definitely have and still use. I need to add an argument ‘cds_version’ to functions to maintain performance for both. Will be doing this soon.

**Comment by dklinges9** [comment]
Hi Ilya,

I've now [merged](https://github.com/dklinges9/mcera5/commit/8205e5d06c68bdbe9a4248a682b65eb72f94c57b) the [new_cds_time_edits](https://github.com/dklinges9/mcera5/tree/new_cds_time_edits) branch into master, after adding modularity so that ERA5 data queried from both old ("legacy") and new versions of the CDS should be possible to handle. I also addressed some of the other outstanding issues with compatibility with different microclimate R packages (e.g. microclima vs micropoint). I haven't yet tested this substantially so please reach out if you have issues.
