### ISSUE TITLE
Frequent, intermittent internal server error when following vignette code 

### ISSUE THREAD

**Issue by Kasi21** [dklinges9/mcera5#39]
Hello, 

I wanted to flag that there seems to be an intermittent issue when running the request_era5 function where after several minutes we get the below error:

Error: internal server error--- check your retry rate!internal server error--- check your retry rate!d#d#90e-71##-4510-97bf-43a##1fbd--- check your retry rate!

(hashed out some of the characters as I'm not sure whether they were for a secure api key or similar). 

I get this error intermittently (~50% of the time) both when running my own bespoke code and the code from your GitHub vignette. In the other 50%, it seems to be working okay and I get the downloaded data in the specified folder. 

Thanks for the package, 

Kas

**Comment by dklinges9** [comment]
Hi Kas,

You're not alone here. I haven't had the chance to thoroughly dig into this (and may not be able to soon), but this error has occurred more frequently since ECMWF switched to their new Climate Data Store (CDS) platform. I wonder if it has to do with a flurry of activity globally on the new platform, and so things are a tad wonky with how API requests are handled.

My guess is this is something that is out-of-scope for `mcera5` itself. A lot of the legwork for the CDS API requests is done in the brilliant package, [ecmwfr](https://github.com/bluegreen-labs/ecmwfr), although this may even be as fundamental as how API requests are handled in `curl`.

I'll keep this issue open for now though, and see what I can do about it.

**Comment by Kasi21** [comment]
Hi Dave, 

Thanks for the update. No problem, I'll work around it for now by downloading directly from Climate Data Store. 

Cheers,

Kas

**Comment by dklinges9** [comment]
Hi Kas,

Has this error persisted for you? It seems other users have been able to download recently without facing this error-- gauging from recent emails to me asking about other mcera5 considerations, but not this error.

**Comment by Kasi21** [comment]
Hi Dave, 

Yes, the error persisted for me, but the severity is intermittent. I've been trying to download 30-years worth of era5 data - somtimes it happens after a few months of data have downloaded and sometimes after a few years. I ended up just monitoring and restarting it from where it failed. I think the most I was able to download was about 36 months of data before it threw the error. 

Right now, the API is completely down for me because the CDS store recently crashed and isn't running at full capacity yet, so I still have about 14 months of data to download.

**Comment by dklinges9** [comment]
Thanks for the update! Yes the CDS has had some issues with crashing recently, which is frustrating and nothing we can do about that. 

I'm going to close this issue because it doesn't seem anything can be done within the scope of the package, but please do keep me posted if other concerns arise.
