### ISSUE TITLE
Issue with functions that require nc_open

### ISSUE THREAD

**Issue by Kasi21** [dklinges9/mcera5#44]
Hi Dave, 

I know the nc_open function isn't your function, but since it's heavily used by your package, I wanted to flag an issue opening .nc files downloaded post the CDS outage. 

For files downloaded pre 2024-11-26, nc_open (and all the downstream functions that require it) work perfectly. However, for files downloaded later, we get the error: 

```
Error in R_nc4_open: NetCDF: Unknown file format
Error in ncdf4::nc_open(x) : 
  Error in nc_open trying to open file Data/era5/study system/1990-2023/seperate/study_system_2008_5.nc (return_on_error= FALSE )
```

This might be related to [this issue](https://forum.ecmwf.int/t/problems-parsing-nc-files-after-outage/8060) raised on the CDS forum and/or to [the update to the format of netCDF files](https://forum.ecmwf.int/t/forthcoming-update-to-the-format-of-netcdf-files-produced-by-the-conversion-of-grib-data-on-the-cds/7772).

I've uploaded a sample of files [you can access here](https://drive.google.com/drive/folders/1qfLrNgr8kNf-5G1yGSTd2XmcQQ-uqL2L?usp=sharing). In the sample data, months 2,3,4 open fine (pre 26 November) and months 5-6 do not open. 

If there is a fix that can be implemented in the era5 package, is it possible to have compatability for all .nc files regardless of when they were downloaded? It's taken a few weeks to download the data I need due to CDS issues, and so it would be great if I can avoid redownloading files. 

Thanks in advance, 

Kas

**Comment by Kasi21** [comment]
Hi Dave, 

I have an update on this. The error isn't with the nc_open function but I think it's to do with how the data from the API is saved (i.e., that it's now split into different .nc files by stepType).

Specifically, the received data is still saved as a .nc file, but I think it should be a zip file due to the changes the CDS made. For example, if you change the extension of the downloaded .nc files to .zip, you see three different NC files within the zip.

That also has follow-on repurcusions for the combine_netcdf function. Is it possible to adjust that function so that regardless of whether the data are in the new or legacy format, you can still combine them?

Thanks, 

Kas

**Comment by dklinges9** [comment]
Hi Kas,

Thanks for bringing this to my attention. Indeed it seems some functionality will need to change, but I should be able to control this within `mcera5`. I'm looking into this now and will be back in touch.

**Comment by dklinges9** [comment]
Hi Kas,

### some context for why the ECMWF CDS made this change:  
Indeed this issue arises because of a [recent update to the CDS](https://forum.ecmwf.int/t/forthcoming-update-to-the-format-of-netcdf-files-produced-by-the-conversion-of-grib-data-on-the-cds/7772): in a nutshell, certain variables are calculated according to different windows of time: some variables are "instantaneous" (i.e. their value corresponds to the value as estimated exactly at the beginning of the hour) while others are "accumulated" (i.e. the sum of many instantaneous values across one hour) or an "average" (the mean of many instantaneous values across one hour). As such these differences entail different ways of handling the time dimension, and so it looks like ECMWF wanted to clean after themselves and provide these different types of variables separately to users.

### Changes to mcera5 to address this:  
I just wrote up a solution and tested it with some new downloads, [in this most recent commit](https://github.com/dklinges9/mcera5/commit/b046d88188656a25c31e237dbb4611a2f3451c96). The `build_era5_request` family of functions now queries the file and saves it as a .zip file (as you suggested). Then within `request_era5`, if the targeted file is indeed a .zip, then this function unzips the .zip and binds together the netCDF files within, saving them as one netCDF. the functionality of `combine_netcdf`, which combines netCDFs that have the _same variables_ but different temporal extents, remains the same, and both types of combinations (binding of different variables, and binding of different temporal extents) occur in sequence as desired by the user.

For the time being, this new functionality doesn't delete the temporary files (eg the intermediate .zip), but I might add that in soon.

### For your situation in particular, Kas, and for others in the same boat:   

agreed that you shouldn't have to re-download files. For those files that you have downloaded since 2024-11-26, I suggest you do the following:
- manually rename each downloaded file to have extenstion ".zip" instead of ".nc"
- apply mcera5's new internal function, `bind_zipped_netcdf`, directly to each of these new .zip files. I kept this function as internal to the package (i.e. it isn't exported when the package is built), but you can simply [copy the code for the function, here,](https://github.com/dklinges9/mcera5/blob/b046d88188656a25c31e237dbb4611a2f3451c96/R/internal.R#L444) to a local script of yours. This will create a new set of netCDF files that should resemble the old set of queried netCDF files, before the CDS starting zipping them.
- If desired, call `combined_netcdf` to your new set of netCDFs
- you should be able to call `extract_clim` or `extract_precip` as before now.


As always, let me know if you run into further troubles. I'll close this issue by the end of the week if it seems resolved on your end.

**Comment by dklinges9** [comment]
Closing per prior comment.
